# Site settings
title: Inside the Machine
subtitle: A Practical Approach to Reverse Engineering for Developers
description: >
  A comprehensive guide to the art of reverse engineering, exploring various techniques and strategies
  to extract valuable insights from software systems.
baseurl: "/inside-the-machine"
url: "https://mohitmishra786.github.io"

# Theme settings
theme: minima

# Author information
author:
  name: Mohit Mishra
  email: immadmohit@gmail.com
  github_username: mohitmishra786

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - LICENSE
  - Part-1-Fundamentals
  - Part-2-Disassembly
  - Part-3-Dynamic-Analysis
  - Part-4-Advanced
  - Part-5-Applications
  - Part-6-Future